chunk:
  size: 20            # Paragraphs per chunk (must be multiple of 5)
  context: 10         # Context paragraphs at start/end of each chunk
  max_convert: 40     # Max paragraphs to convert (multiple of 5, >= chunk size; use 1000000 for whole book)

character:
  narrator: true  # Include narrator in character list
  unknown: true  # Include unknown in character list

entity_detection:
  model: "flair/ner-english-large"  # Use "flair/ner-english-fast" if program crashes or if you have low VRAM
  confidence: 0.9    # Lower: more false detections; Higher: might miss characters (for "ner-english-large" use 0.9, for "ner-english-fast" use 0.5)

summarization:
  gemini: false  # Uses kobold to summarize if false

api:
  kobold: "http://localhost:5001/api/"
  gemini: "your api key"

other:
  debug: false
